export const juniorDeveloperProjects = {
  level: `Junior Developer`,
  hourlyRate: 25,
  approximateHours: 40,
  description: `I record every lesson for you to keep forever, and You can quit whenever. By the end of the last project you will be able to apply to Junior Developer, WordPress Developer Positions or Start Light FreeLancing or Tutoring Younger Developers.`,
  salary: `MINIMUM $30,000 - $60,000 or MINIMUM $10 - $20 an hour.`,

  techStack: {
    description: `These are the technologies you will learn by the end of the last project:`,
    technologies: [
      `HTML - HyperText Markup Language`,
      `HTML5`,
      `CSS - Cascading Style Sheets`,
      `CSS3`,
      `Git`,
      `XML - Extensible Markup Language`,
      `Saas - Software As A Service`,
      `SASS - Syntactically Awesome Style Sheets`,
      `Compilers`,
      `Extensions`,
      `Plugins`,
      `IDE - Integrated Development Environment`,
      `VS Code - Visual Studio Code`,
      `Codepen`,
      `Brackets.io`,
      `Atom Editor`,
      `Sublime Text`,
      `CLI - Command Line Interface`,
      `JS - JavaScript`,
      `ES - EcmaScript 2022`,
      `SPA - Single Page Application`,
      `Modern JS`,
      `Libraries`,
      `Frameworks`,
      `jQuery`,
      `WordPress Advanced Custom Fields`,
      `JSON - JavaScript Object Notation`,
      `AJAX - Asyncronous JavaScript & XML`,
      `API - Application Programming Interface`,
      `RESTFUL API`,
      `Cache Storage`,
      `Best Practicies`,
      `Syntax`,
      `Resume`,
      `Portfolio`,
      `Fetch`,
      `HTTP Request`,
      `Async Await`,
      `Procreate`,
      `Design`,
      `Mock Up`,
      `Flowchart`,
      `Effects`,
      `Animations`,
      `UI/UX - User Interaction/User Experience`,
      `jQuery UI`,
      `Accessibilty`,
      `Section 508 ADA Compliance`,
      `Color Theory`,
      `Coolors`,
      `Stock Images`,
      `Repositories`,
      `Stock Photography`,
      `Pexels`,
      `Pixabay`,
      `Unsplash`,
      `Font Awesome`,
      `Flaticon`,
      `Envato`,
      `Figma`,
      `Axure`,
      `Adobe XD - Experience Designer`,
      `PhotoShop`,
      `Illustrator`,
      `After Effects`,
      `Functional Programming`,
      `BDD - Behavior Driven Development`,
      `Node.js`,
      `NPM - Node Package Manager`,
      `PHP - Hypertext Preprocessor | Personal Home Page`,
      `Theme Development`,
      `Templating`,
      `Bootstrap`,
      `TailWind`,
      `Material UI`,
      `Apache`,
      `XAMPP`,
      `Heroku`,
      `TS - TypeScript`,
      `Database`,
      `Authorization`,
      `User Registration`,
      `Full Stack Apps`,
      `Baas - Backend As A Service`,
      `Google API`,
      `Google Maps`,
      `Google Firebase`,
      `Object Oriented Programming (OOP)`,
      `Linux, Apache, MySQL, and PHP (LAMP)`,
      `Agile Methodology`,
      `Scrum Methodology`,
      `Waterfall Methodology`,
      `Collaberation`,
      `Contribution`,
      `Source Control`,
      `Open Source`,
      `CI/CD`,
      `Kanban`,
      `HubSpot`,
      `Tickets`,
      `Issues`,
      `Monday`,
      `CRM`,
    ],
  },

  projects: [
    {
      title: `Developer Enviornment`,
      approximateHours: 1,
      approximateCost: 1 * 25,
      description: `We start the course by introducing ourselves to eachother and then getting the workspace set up and organized for how we will work across the courses and projects.`,
      picture: `https://github.com/strawhat19/Tutoring-Packages/blob/main/public/assets/images/development-environments.JPG?raw=true`,
      demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
      technologies: [`CodePen`, `VS Code`, `Git Bash`, `SSH`, `Apache`, `XAMPP`, `SASS Compiler`, `Live Server`, `htdocs`, `CLI`, `mkdir`, `touch`, `cd`, `rm rf`, `Adobe Creative Cloud`, `Github`, `Github Pages`, `Heroku`, `Firebase`],
    },{
      title: `Counter Demo`,
      approximateHours: 0.5,
      approximateCost: 0.5 * 25,
      description: `Light Intro to the course, HTML, CSS, and JavaScript in Codepen`,
      picture: `https://reactjsexample.com/content/images/2019/01/Counter-react-component-with-animation.gif`,
      demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
      technologies: [`HTML`, `CSS`, `JavaScript`, `jQuery`, `Codepen`],
    },
    {
      title: `Email Signature in Gmail`,
      approximateHours: 1,
      approximateCost: 1 * 25,
      description: `Make a Simple Email Signature in VS Code`,
      picture: `https://github.com/strawhat19/Tutoring-Packages/blob/main/public/assets/images/emailSignatures.JPG?raw=true`,
      demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
      technologies: [`HTML`, `CSS`, `VS Code`],
    },
    {
      title: `Rock, Paper, Scissors`,
      approximateHours: 1.5,
      approximateCost: 1.5 * 25,
      description: `Intro to Game Development, Github, and Fusion of HTML, CSS, PHP, SASS, JavaScript & Project Management`,
      picture: `https://raw.githubusercontent.com/strawhat19/Rock-Paper-Scisssors/main/assets/images/Rock-Paper-Scissors-Application.png`,
      demo: `https://strawhat19.github.io/Rock-Paper-Scisssors/`,
      technologies: [
        `HTML`,
        `CSS`,
        `PHP`,
        `SASS`,
        `PHP`,
        `JavaScript`,
        `jQuery`,
        `TypeScript`,
        `VS Code`,
        `Game Development`,
        `Project Management`,
      ],
    },
    {
      title: `Discord Bots`,
      approximateHours: 2,
      approximateCost: 2 * 25,
      description: `Intro to Discord Bot Development, Hosting & Deployment`,
      picture: `https://github.com/strawhat19/Discord-Bots/raw/main/UpLift/assets/screenshotWOTD.JPG`,
      demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
      technologies: [`JavaScript`, `VS Code`, `Discord Bot Development`],
    },
    {
      title: `WordPress Business Website`,
      approximateHours: 2,
      approximateCost: 2 * 25,
      description: `Intro to WordPress by Building a Business Website & Application`,
      picture: `https://github.com/strawhat19/Tutoring-Packages/blob/main/public/assets/images/wordPressBusiness.JPG?raw=true`,
      demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
      technologies: [`HTML`, `CMS`, `WordPress`, `CSS`, `BDD`],
    },
    {
      title: `Password Generator`,
      approximateHours: 2,
      approximateCost: 2 * 25,
      description: `Intro to Functional Programming, Data Types and Data Array & Object Manipulation`,
      picture: `https://github.com/strawhat19/Password-Generator/raw/main/assets/images/screenshot.png`,
      demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
      technologies: [
        `HTML`,
        `Functional Programming`,
        `Data Types`,
        `CSS`,
        `PHP`,
        `JavaScript`,
        `jQuery`,
        `TypeScript`,
        `Array & Object Manipulation`,
      ],
    },
    {
      title: `Google Chrome No Internet Dinosaur Game`,
      approximateHours: 2.5,
      approximateCost: 2.5 * 25,
      description: `Advanced JavaScript Game Development`,
      picture: `https://miro.medium.com/max/1200/1*kUaj2XZF0R75duI7Lskt2w.gif`,
      demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
      technologies: [`HTML`, `CSS`, `JavaScript`, `jQuery`, `Game Development`],
    },
    {
      title: `Jr. Dev Portfolio`,
      approximateHours: 3,
      approximateCost: 3 * 25,
      description: `Simple Single Page Application, Which We Will Be Making Updates To Throughout The Course`,
      picture: `https://github.com/strawhat19/Portfolio/blob/main/assets/images/design/landscapeDesign.png?raw=true`,
      demo: `https://strawhat19.github.io/Portfolio/`,
      technologies: [
        `HTML`,
        `SPA`,
        `CSS`,
        `SASS`,
        `PHP`,
        `JavaScript`,
        `jQuery`,
        `TypeScript`,
        `API`,
        `Fetch`,
        `JSON`,
        `AJAX`,
        `Async Await`,
        `Array & Object Manipulation`,
        `Photoshop`,
        `Illustrator`,
        `Procreate`,
        `Figma`,
      ],
    },
    {
      title: `Hangman`,
      approximateHours: 4,
      approximateCost: 4 * 25,
      description: `A Word Guessing Game With A Timer`,
      picture: `https://github.com/strawhat19/Word-Guessing-Game/raw/main/assets/images/Word-Guess-Application-Image.png`,
      demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
      technologies: [
        `HTML`,
        `CSS`,
        `SASS`,
        `PHP`,
        `JavaScript`,
        `jQuery`,
        `TypeScript`,
        `Game Development`,
      ],
    },
    {
      title: `Who Wants To Be A Millionaire`,
      approximateHours: 5,
      approximateCost: 5 * 25,
      description: `A Quiz Like Trivia Game with Registration and a Database with Storage`,
      picture: `https://github.com/strawhat19/Coding-Quiz/raw/main/assets/images/Official-Code-Quiz-Application.png`,
      demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
      technologies: [
        `HTML`,
        `CSS`,
        `SASS`,
        `PHP`,
        `JavaScript`,
        `jQuery`,
        `TypeScript`,
        `Game Development`,
      ],
    },
    {
      title: `Weather App`,
      approximateHours: 7,
      approximateCost: 7 * 25,
      description: `A Fully Function Weather App Which We Will Turn into a Mobile Application as Well`,
      picture: `https://github.com/strawhat19/Weather-App/raw/main/assets/css/images/designs/WeatherAppFinaleRounded.png`,
      demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
      technologies: [
        `HTML`,
        `CSS`,
        `SASS`,
        `PHP`,
        `JavaScript`,
        `jQuery`,
        `TypeScript`,
        `API`,
        `Google API`,
        `Google Maps`,
        `Fetch`,
        `JSON`,
        `AJAX`,
        `Async Await`,
        `Array & Object Manipulation`,
      ],
    },
    {
      title: `Project Planner`,
      approximateHours: 9,
      approximateCost: 9 * 25,
      description: `An Intro to Full Stack Development with a Mix of Project Tracker & Day Planner with User Registration & Data Store`,
      picture: `https://github.com/strawhat19/Project-Tracker/raw/main/assets/images/ProjectTrackerApplication-LightMode.png`,
      demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
      technologies: [
        `HTML`,
        `CSS`,
        `SASS`,
        `PHP`,
        `JavaScript`,
        `jQuery`,
        `TypeScript`,
        `API`,
        `Fetch`,
        `JSON`,
        `AJAX`,
        `Async Await`,
        `Array & Object Manipulation`,
        `Object Oriented Programming`,
        `User Registration`,
        `Authorization`,
        `Firebase`,
        `Baas`,
        `Database`,
        `Full Stack Development`,
      ],
    },
    {
      title: `WordPress Portfolio`,
      approximateHours: 0.5,
      approximateCost: 0.5 * 25,
      description: `SPA Simple WordPress Portfolio and A Chance to Relax, You can see how Fast you Code now!`,
      picture: `https://github.com/strawhat19/Tutoring-Packages/blob/main/public/assets/images/piratechs.JPG?raw=true`,
      demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
      technologies: [
        `HTML`,
        `CMS`,
        `WordPress`,
        `CSS`,
        `JavaScript`,
        `jQuery`,
        `TypeScript`,
        `API`,
        `Fetch`,
        `JSON`,
        `AJAX`,
        `Async Await`,
        `Array & Object Manipulation`,
      ]
    }
  ]
}