export const fullStackDeveloperProjects = {
    level: `Full Stack Developer`,
    hourlyRate: 25,
    approximateHours: 50,
    description: `I record every lesson for you to keep forever, and You can quit whenever. By the end of the last project you will be able to apply to Full Stack or Front End Developer Positions or Start Serious FreeLancing or Tutoring as a Business or Side Hustle or become a Mobile App or Game Developer, I myself was at this level for 5 years making $40,000 in year 1 to $75,000 by year 5 (Right Now 2022) and I'm currently interviewing for Senior Level Positions ranging from $90,000 - $200,000.`,
    salary: `MINIMUM $60,000 - $150,000 or MINIMUM $20 - $30 an hour.`,
  
    techStack: {
      description: `These are the technologies you will learn by the end of the last project:`,
      technologies: [
        `CMS`,
        `Wix`,
        `Domains`,
        `Hosting`,
        `Shopify`,
        `SquareSpace`,
        `Python`,
        `PyCharm`,
        `Payment Gateways`,
        `Stripe`,
        `Square`,
        `Paypal`,
        `WordPress`,
        `OBS - Open Broadcast Software`,
        `Plugin Development`,
        `C# - C Sharp`,
        `C++ - C Plus Plus`,
        `Unity - Usually for Simple Game Development with C#`,
        `Unreal Engine - Usually for Complex or Console Game Development with C++`,
        `MVC - Models Views Controllers Architecture`,
        `SEO - Search Engine Optimization`,
        `Performance`,
        `Auditing`,
        `Web Scrapers`,
        `Social Feeds`,
        `Google Analytics`,
        `Webflow`,
        `React`,
        `Mobile Development`,
        `PWA - Progressive Web App`,
        `React Native`,
        `Dart`,
        `Flutter`,
        `Kotlin`,
        `Android Studio`,
        `Swift`,
        `XCode - iOS Apps`,
        `JSX - JavaScript & XML`,
        `TSX - TypeScript & XML`,
        `Transpilers`,
        `Test Driven Development (TDD)`,
        `Express`,
        `HBS - HandleBars`,
        `MongoDB`,
        `MERN - MongoDB, Express, React, Node`,
        `MEAN - MongoDB, Express, Angular, Node`,
        `SQL - Structured Querying Language`,
        `NoSQL`,
        `Draggable.js`,
        `Three.js - Making 3D JavaScript Objects, Works Well with Blendr on the Web`,
        `Next.js`,
        `Solid.js`,
        `Vue.js`,
        `Gatsby.js`,
        `Angular`,
      ],
    },
  
    projects: [
      {
        title: `Tic Tac Toe`,
        approximateHours: 1,
        approximateCost: 1 * 25,
        description: `Intro to React Game Development & State Management`,
        picture: `https://camo.githubusercontent.com/79bf2e1e37edb2aae2010927a60f900128282650983637d8acf4a2bfac091602/687474703a2f2f692e67697068792e636f6d2f6c30457863417a3442757563416a7837792e676966`,
        demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
        technologies: [
          `React`,
          `HTML`,
          `CSS`,
          `JavaScript`,
          `jQuery`,
          `TypeScript`,
          `Game Development`,
          `State Management`,
        ],
      },
      {
        title: `Dashboard`,
        approximateHours: 2,
        approximateCost: 2 * 25,
        description: `Refresher on Front End Development`,
        picture: `https://raw.githubusercontent.com/app-generator/static/master/admin-dashboards/react-dashboard-material-admin-flatlogic-intro.gif`,
        demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
        technologies: [
          `HTML`,
          `CSS`,
          `SASS`,
          `PHP`,
          `JavaScript`,
          `jQuery`,
          `TypeScript`,
          `VS Code`,
        ],
      },
      {
        title: `README and Team Profile Generator`,
        approximateHours: 3,
        approximateCost: 3 * 25,
        description: `Intro to Node CLI Apps`,
        picture: `https://github.com/strawhat19/Team-Profile-Generator/raw/main/images/step9.gif`,
        demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
        technologies: [`Node.js`, `NPM`, `CLI`, `JavaScript`, `TDD`, `Jest`],
      },
      {
        title: `Notetaker`,
        approximateHours: 3,
        approximateCost: 3 * 25,
        description: `Intro to RESTFUL API Development`,
        picture: `https://github.com/strawhat19/NoteTaker/raw/main/public/assets/images/noteTakerFinal.jpg`,
        demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
        technologies: [
          `HTML`,
          `CSS`,
          `SASS`,
          `PHP`,
          `Express`,
          `JavaScript`,
          `jQuery`,
          `TypeScript`,
          `VS Code`,
          `RESTFUL API Development`,
          `Database`,
          `JSON`,
          `API Development`,
        ],
      },
      {
        title: `Tune Time | Spotify Playlist Generator`,
        approximateHours: 3.5,
        approximateCost: 3.5 * 25,
        description: `A Spotify Playlist Generator, and a Good Intro to MVC Architecture, SQL, Express & Handlebars`,
        picture: `https://github.com/d4nnyq88/tune-time/raw/main/public/images/dashboardOfficial.jpg`,
        demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
        technologies: [
          `HTML`,
          `CSS`,
          `SASS`,
          `MVC`,
          `SQL`,
          `JavaScript`,
          `jQuery`,
          `TypeScript`,
          `VS Code`,
          `Express`,
          `Handlebars`,
          `API`,
          `Fetch`,
          `JSON`,
          `AJAX`,
          `Async Await`,
          `Array & Object Manipulation`,
          `Object Oriented Programming`,
          `User Registration`,
          `Authorization`,
          `Database`,
          `Full Stack Development`,
        ],
      },
      {
        title: `What's Your Deal!?`,
        approximateHours: 4.5,
        approximateCost: 4.5 * 25,
        description: `Stocks Investment App, Intro to MongoDB, Express, React, React Hooks, Context API, Node, MERN Stack`,
        picture: `https://raw.githubusercontent.com/strawhat19/Whats-Your-Deal/main/client/public/assets/screenshot2.JPG`,
        demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
        technologies: [
          `HTML`,
          `CSS`,
          `SASS`,
          `NoSQL`,
          `JavaScript`,
          `jQuery`,
          `TypeScript`,
          `VS Code`,
          `MongoDB`,
          `React`,
          `Context API`,
          `React Hooks`,
          `Express`,
          `API`,
          `Fetch`,
          `JSON`,
          `AJAX`,
          `Async Await`,
          `Array & Object Manipulation`,
          `Object Oriented Programming`,
          `User Registration`,
          `Authorization`,
          `Database`,
          `Full Stack Development`,
        ],
      },
      {
        title: `Netflix Clone`,
        approximateHours: 5,
        approximateCost: 5 * 25,
        description: `Deep Dive into React, Redux, Firebase & TSX`,
        picture: `https://github.com/strawhat19/react-netflix-clone/raw/main/public/assets/design5.jpg`,
        demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
        technologies: [
          `HTML`,
          `CSS`,
          `SASS`,
          `NoSQL`,
          `JavaScript`,
          `jQuery`,
          `TypeScript`,
          `VS Code`,
          `Firebase`,
          `Baas`,
          `React`,
          `Redux`,
          `Context API`,
          `React Hooks`,
          `API`,
          `Fetch`,
          `JSON`,
          `AJAX`,
          `Async Await`,
          `Array & Object Manipulation`,
          `Object Oriented Programming`,
          `User Registration`,
          `Authorization`,
          `Database`,
          `Full Stack Development`,
        ],
      },
      {
        title: `WordPress Custom Blog`,
        approximateHours: 5.5,
        approximateCost: 5.5 * 25,
        description: `Deep Dive into WordPress Theme Development, Plugin Development & Advanced Custom Fields`,
        picture: `https://github.com/strawhat19/Tutoring-Packages/blob/main/public/assets/images/PPN.JPG?raw=true`,
        demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
        technologies: [
          `WordPress`,
          `HTML`,
          `CSS`,
          `SASS`,
          `PHP`,
          `JavaScript`,
          `jQuery`,
          `WordPress Theme Development`,
          `Plugin Development`,
          `Advanced Custom Fields`,
        ],
      },
      {
        title: `MyDex | Pokedex Clone`,
        approximateHours: 7.5,
        approximateCost: 7.5 * 25,
        description: `A Pokedex Clone with Advanced Full Stack Development, React, Redux, Firebase & TSX`,
        picture: `https://github.com/strawhat19/MyDex-Pokedex-Clone/raw/main/assets/images/design2.JPG`,
        demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
        technologies: [
          `HTML`,
          `CSS`,
          `SASS`,
          `NoSQL`,
          `JavaScript`,
          `jQuery`,
          `TypeScript`,
          `VS Code`,
          `Firebase`,
          `Baas`,
          `React`,
          `Redux`,
          `Context API`,
          `React Hooks`,
          `API`,
          `Fetch`,
          `JSON`,
          `AJAX`,
          `Async Await`,
          `Array & Object Manipulation`,
          `Object Oriented Programming`,
          `User Registration`,
          `Authorization`,
          `Database`,
          `Full Stack Development`,
        ],
      },
      {
        title: `Sanctuary Game Development`,
        approximateHours: 10,
        approximateCost: 10 * 25,
        description: `Advanced Game Development with Unity, we make an entire game`,
        picture: `https://raw.githubusercontent.com/strawhat19/Portfolio/main/assets/images/graphics/Sanctuary-Art.png`,
        demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
        technologies: [
          `Unity`,
          `C#`,
          `Photoshop`,
          `Illustrator`,
          `Procreate`,
          `Figma`,
          `Game Development`,
          `Source Control`,
          `Unity Collaboration`,
        ],
      },
      {
        title: `React / Vue.js / Angular Full Stack Developer Portfolio`,
        approximateHours: 5,
        approximateCost: 5 * 25,
        description: `Advanced Modern JS Framework Development and you can see how fast you code`,
        picture: `https://raw.githubusercontent.com/strawhat19/React-Portfolio/main/public/assets/develeporMode2.JPG`,
        demo: `https://strawhat19.github.io/Piratechs-Email-Signatures/`,
        technologies: [
          `HTML`,
          `CSS`,
          `SASS`,
          `NoSQL`,
          `JavaScript`,
          `jQuery`,
          `TypeScript`,
          `VS Code`,
          `Firebase`,
          `Baas`,
          `React`,
          `Redux`,
          `Context API`,
          `React Hooks`,
          `API`,
          `Fetch`,
          `JSON`,
          `AJAX`,
          `Async Await`,
          `Array & Object Manipulation`,
          `Object Oriented Programming`,
          `User Registration`,
          `Authorization`,
          `Database`,
          `Full Stack Development`,
          `Next.js`,
          `Solid.js`,
          `Vue.js`,
          `Gatsby.js`,
          `Angular`,
        ],
      },
    ],
  };